version: '3.1'

services:

  wordpress:
    image: wordpress
    restart: always
    ports:
      - 8001:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: kubeuser
      WORDPRESS_DB_PASSWORD: kubepwd
      WORDPRESS_DB_NAME: kubedb
    volumes:
      - wordpress:/var/www/html

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: kubedb
      MYSQL_USER: kubeuser
      MYSQL_PASSWORD: kubepwd
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql

volumes:
  wordpress:
  db:
